I have observed a tendency in those new to Python to write in a procedural, nested-loop-heavy, index-heavy style reminiscent of C, Fortran, or Matlab. Matlab was heavily influenced by Fortran and both C and Fortran are fairly low-level languages in which this style is often necessary. Python, however, is a high-level scripting language and has preferred alternatives to this style. Indices should be avoided, and can be avoided in most cases. A weaker, but similar statement can be made for loops, and in particular nested loops. In general, you should read and follow [PEP8](https://www.python.org/dev/peps/pep-0008/#code-lay-out) - the canonical python style guide.

Since the style guide is rather long, and very general, I have compiled some examples comparing pythonic and non-pythonic code.

When in doubt, remember this.

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [3]:
import numpy as np

# Unpacking

It is a common occurrence in scientific codes to update variables. Often the procedural nature of our programming languages necessitate steps to be taken in a particular order, or for us to use temporary variables. Python supports tuple/list unpacking that greatly improves readability in these cases.

### Example - Row Swapping
Suppose we wish to swap the first and last row of a matrix. This would be the C style approach - very unpythonic.

In [15]:
A = np.arange(30).reshape((6,5))
print(A)

i1 = 0
i2 = A.shape[0]-1 # last row index
num_cols = A.shape[1]
for i in range(num_cols):
    temp = A[i1, i]
    A[i1, i] = A[i2, i]
    A[i2, i] = temp
print(f'\nRows {i1} and {i2} have been swapped.\n')
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Rows 0 and 5 have been swapped.

[[25 26 27 28 29]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [ 0  1  2  3  4]]


Here is a more pythonic version. We use unpacking to make multiple assignment statements simultaneously without declaring a temporary variable. This works by computing each expression in the right hand side with the current environment, and after the values have been computed we store them in variables on the right hand side.

In [36]:
A = np.arange(30).reshape((6,5))
print(A)

num_cols = A.shape[1]
for col_index in range(num_cols):
    A[0, col_index], A[-1, col_index] = A[-1, col_index], A[0, col_index]
print(f'\nThe first and last rows have been swapped.\n')
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

The first and last rows have been swapped.

[[25 26 27 28 29]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [ 0  1  2  3  4]]


Of course, Numpy supports row slicing, so the best method is this.

In [37]:
A = np.arange(30).reshape((6,5))
print(A)

A[0], A[-1] = A[-1], A[0]

print(f'\nThe first and last rows have been swapped.\n')
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

The first and last rows have been swapped.

[[25 26 27 28 29]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


### Example - Fibonacci

Here is a C-style way to compute Fibonacci numbers. Not very pythonic.

In [38]:
x1 = 0
x2 = 1
print(x1)
print(x2)
for i in range(8):
    temp = x2
    x2 = x1 + x2
    x1 = temp
    print(x2)

0
1
1
2
3
5
8
13
21
34


Here is a more pythonic version. Notice that we use unpacking to update both variables simultaneously. This reduces the number of lines and the need for the temporary variable. Also, the loop counter is not used, so we use the variable name `_` to indicate to human readers that it is not important.

In [39]:
x1, x2 = 0, 1
print(x1)
print(x2)
for _ in range(8):
    x1, x2 = x2, x1+x2
    print(x2)

0
1
1
2
3
5
8
13
21
34


# Indices and Iteration

Generally, avoid looping over indices unless absolutely necessary. In fact, avoid looping syntax when possible in favor of list comprehensions or generator expressions. 

### Sum of Squares

Here is a C-style way of find the sum of the squares of list elements. Not very pythonic.

In [73]:
my_list = list(range(10**2))

In [76]:
SOS = 0
for i in range(len(my_list)):
    SOS += my_list[i]**2
print(SOS)

328350


Here is a more pythonic version. Notice that we are not using indices, and we have replaced the loop in favor of a generator expression. We have also replaced the abbreviated name `SOS` with a more explicit variable name `sum_of_squares`. This last point is more of a recommendation; in scientific computing we often have common, well-known abbreviations. Use your best judgment. 

In [78]:
sum_of_squares = sum(x**2 for x in my_list)
print(sum_of_squares)

328350


### Differentiating a Polynomial

Here is a C-style code that differentiates a polynomial given as a list of coefficients. Not very pythonic.

In [96]:
p = [1, 0, 4, 2, -3, 7] # representing 1 + 4x^2 +2x^3 - 3x^4 + 7x^5
# compute the dervative
pdx = []
for i in range(1, len(p)):
    pdx.append( i*p[i] )
print(pdx)
# print the string representation
pdx_string = ''
for i in range(len(pdx)):
    pdx_string += f'{pdx[i]}x^{i} + '
pdx_string = pdx_string[:-3] # remove final plus sign
print(pdx_string)

[0, 8, 6, -12, 35]
0x^0 + 8x^1 + 6x^2 + -12x^3 + 35x^4


Here is a more pythonic version of the same code. In differentiating these polynomials, the index represents the exponent on the variable, and thus we must use it to compute the derivative. In this case, we use the `enumerate` function to get the index and the coefficient rather than indexing. We also refer to the index as `power` because that is a more informative name in this context. 

We avoid looping here by using a list comprehension and a generator expression.

We also use the `join` function of the string object with a generator expression to combine terms with plus signs between them. This avoids the need for looping, and the need to remove the final plus sign. 

We also define functions to differentiate and create the string representations. Not only are they reusable, but they provide a natural way to organize the code. The function names effectively replace the comments in the above example. Generally, you should not need to comment your code. If your code is complex enough that it needs a comment, consider rewriting it so that it is more clear what it does. Expressive variable and function names can replace most comments. This is good advice for general code, however, it can be appropriate to use comments in certain circumstances. Use your best judgment in deciding what is most clear.

In [98]:
polynomial = [1, 0, 4, 2, -3, 7] # representing 1 + 4x^2 +2x^3 - 3x^4 + 7x^5

def polynomial_differentiate(poly):
    return [power*coeff 
            for power, coeff in enumerate(poly)
            if power is not 0]

derivative = polynomial_differentiate(polynomial)
print(derivative)

def polynomial_to_string(poly):
    terms = (f'{coeff}x^{power}' 
             for power, coeff in enumerate(poly))
    return ' + '.join(terms)

print(polynomial_to_string(derivative))

[0, 8, 6, -12, 35]
0x^0 + 8x^1 + 6x^2 + -12x^3 + 35x^4


# Nested Iteration

In scientific computing, we often nest loops several levels deep. Here is an example that prints all third degree polynomials with unit coefficients in $\mathbb{R}^3$. This is not an efficient way to find them, rather it is a motivating example as it has excessive indentation. It is not pythonic.

In [128]:
for i in range(4):
    for j in range(4):
        for k in range(4):
            if i + j + k == 3:
                print(f'x^{i} * y^{j} * z^{k}')

x^0 * y^0 * z^3
x^0 * y^1 * z^2
x^0 * y^2 * z^1
x^0 * y^3 * z^0
x^1 * y^0 * z^2
x^1 * y^1 * z^1
x^1 * y^2 * z^0
x^2 * y^0 * z^1
x^2 * y^1 * z^0
x^3 * y^0 * z^0


We can avoid nesting loops by using the `product` function from the `itertools` package. We also include our filtering conditional in the generator expression. Note how we use more descriptive variable names for the printing loop. Also note that we have avoided *magic numbers* in favor of giving them variable names `target_degree` and `dimension`.

In [171]:
from itertools import product
target_degree = 3
polynomial_dimension = 3
exponent_generator = (exponents 
                      for exponents in product(range(target_degree+1), repeat=polynomial_dimension)
                      if sum(exponents) == target_degree)

for x_power, y_power, z_power in exponent_generator:
    print(f'x^{x_power} * y^{y_power} * z^{z_power}')

x^0 * y^0 * z^3
x^0 * y^1 * z^2
x^0 * y^2 * z^1
x^0 * y^3 * z^0
x^1 * y^0 * z^2
x^1 * y^1 * z^1
x^1 * y^2 * z^0
x^2 * y^0 * z^1
x^2 * y^1 * z^0
x^3 * y^0 * z^0


### Example - Sum of Cubes

The following example is a C-style way of finding all non-negative integers that are the sum of three non-negative cubes below a particular bound, and counting them.

In [156]:
N = 100
bound = math.ceil(N**(1/3))
sum_of_cubes = []
for i in range(bound):
    for j in range(bound):
        for k in range(bound):
            n = i**3 + j**3 + k**3
            if n >= N:
                continue
            # check if it's already in the list
            in_list = False
            for l in range(len(sum_of_cubes)):
                if n == sum_of_cubes[l]:
                    in_list = True
                    break
            if not in_list:
                sum_of_cubes.append(n)
print(sum_of_cubes)
print(f'There are {len(sum_of_cubes)} numbers less than {N} which are themselves a sum of three non-negative cubes.')

[0, 1, 8, 27, 64, 2, 9, 28, 65, 16, 35, 72, 54, 91, 3, 10, 29, 66, 17, 36, 73, 55, 92, 24, 43, 80, 62, 99, 81]
There are 29 numbers less than 100 which are themselves a sum of three non-negative cubes.


Here is a more pythonic example. Note that we again use the `combinations_with_replacement` function to avoid the looping. We also use nested generator expressions. It might be advisable to separate these and name the inner expression `unfiltered_sum_of_cubes` for example. We also use the python `set` data type to ensure we have unique values. Another way to do this (if another data structure is preferred) is to use the keyword `in`, however the set data type uses hash tables and thus has $\mathcal{O}(1)$ lookup. The set data type also has the advantage of sorting the values for free when the string representation is formed by the `print` function.

In [168]:
N = 100
import math
from itertools import combinations_with_replacement
bound = math.ceil(N**(1/3))
sum_of_cubes = {n for n in 
                (x**3+y**3+z**3 for x, y, z in combinations_with_replacement(range(bound+1), 3))
                if n < N}
print(sum_of_cubes)
print(f'There are {len(sum_of_cubes)} numbers less than {N} which are themselves a sum of three non-negative cubes.')

{0, 1, 2, 3, 8, 9, 10, 16, 17, 24, 27, 28, 29, 35, 36, 43, 54, 55, 62, 64, 65, 66, 72, 73, 80, 81, 91, 92, 99}
There are 29 numbers less than 100 which are themselves a sum of three non-negative cubes.
